version: '3'
services:
  redis-server:
    image: 'redis'
  node-app:
    build: .
    ports:
    - '4001:8081'
    volumes:
      - /node_modules
      - .:/app
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    # depends_on:
    #   - postgres

  # postgres:
  #   image: 'postgres:latest'
  #   environment:
  #     - POSTGRES_PASSWORD=postgres_password